### ISSUE TITLE
Clicking on the link "The Internet's Own Boy" does not navigate the reader to the actual YouTube documentary.

### ISSUE THREAD

**Issue by avin82** [rwxrob/zet#3]
**Steps to reproduce**

1. Navigate to [this](https://github.com/rwxrob/zet/tree/main/20210506164209) page of the boost.
2. Click the link "The Internet's Own Boy"

**Expected Result**
Reader should be navigated to the actual [YouTube documentary](https://www.youtube.com/watch?v=9vz06QO3UkQ&t=26s)

**Actual Result**
Reader is navigated to [Rob's YouTube channel](https://www.youtube.com/c/rwxrob/search)

**Comment by rwxrob** [comment]
Thanks for pointing this out. I think I was trying to search out all my videos where I refer to Aaron, but this is far better.
