### ISSUE TITLE
What's the CLI tool you use? I don't see jekyll config, how would I get something like this set up?

### ISSUE THREAD

**Issue by talksik** [rwxrob/zet#34]
Hey Rob!

This site is minimal and awesome. Do you have a runbook? It seems like you have a lot of tools locally that you may be relying on to create things like the index and also to create new notes.

Thank you!

**Comment by AugustasV** [comment]
@talksik for indexing and creating new notes I think he is still using keg tool https://github.com/rwxrob/keg

**Comment by talksik** [comment]
Thanks @AugustasV !! I ended up learning how basic Jekyll works and using [this template](https://github.com/chadbaldwin/simple-blog-bootstrap) for the whole setup.
