### ISSUE TITLE
Factual inacurracy in 20210502133019

### ISSUE THREAD

**Issue by brownbishop** [rwxrob/zet#9]
The legacy Perl interface wasn't dropped in NeoVim.

> Nvim supports Perl |remote-plugin|s on Unix platforms. Support for polling STDIN
on MS-Windows is currently lacking from all known event loop implementations.
The Vim legacy |perl-vim| interface is also supported (which is itself
implemented as a Nvim remote-plugin).

https://neovim.io/doc/user/provider.html

**Comment by rwxrob** [comment]
That's not what the release notes say. Turning it into a plugin is not the same as not dropping in, agreed. But it still kinda is.
